
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: linxuelei
    password: Lei421120
    url: jdbc:mysql://rm-m5eov9qgch4551891mo.mysql.rds.aliyuncs.com:3306/test?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      connection-timeout: 2000
      maximum-pool-size: 20
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      max-lifetime: 570000
      idle-timeout: 500000

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml